apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gassouma530975/testdeploy:back2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: secret-volume
              mountPath: "/etc/secrets"
              readOnly: true

      volumes:
        - name: secret-volume
          secret:
            secretName: db-credentials

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: development
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: backend

