apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gassouma530975/testdeploy:frontendv16
          ports:
            - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: development
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: frontend


